// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmN-Cx9DZYT_QPdkypKbBBC22V2PftTM',
    appId: '1:298422184945:web:1a4d2d611d0b06a6513250',
    messagingSenderId: '298422184945',
    projectId: 'cs2-investment-tracker',
    authDomain: 'cs2-investment-tracker.firebaseapp.com',
    storageBucket: 'cs2-investment-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8pPfgXpcBafQwA8qijmrp6KrLvO5qciQ',
    appId: '1:298422184945:android:7a221cb149bc00a0513250',
    messagingSenderId: '298422184945',
    projectId: 'cs2-investment-tracker',
    storageBucket: 'cs2-investment-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRCmgm37A9FU8QTwfYsO_hOD7RvGj2Vs',
    appId: '1:298422184945:ios:a08755de32968411513250',
    messagingSenderId: '298422184945',
    projectId: 'cs2-investment-tracker',
    storageBucket: 'cs2-investment-tracker.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRCmgm37A9FU8QTwfYsO_hOD7RvGj2Vs',
    appId: '1:298422184945:ios:a08755de32968411513250',
    messagingSenderId: '298422184945',
    projectId: 'cs2-investment-tracker',
    storageBucket: 'cs2-investment-tracker.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdmN-Cx9DZYT_QPdkypKbBBC22V2PftTM',
    appId: '1:298422184945:web:6bb06d08f9f9ea86513250',
    messagingSenderId: '298422184945',
    projectId: 'cs2-investment-tracker',
    authDomain: 'cs2-investment-tracker.firebaseapp.com',
    storageBucket: 'cs2-investment-tracker.firebasestorage.app',
  );
}
